import React from 'react';
import { useMediaQuery } from 'react-responsive';
import ResearchPic1 from '../photos/ocean-ice-shell-mystery.png';
import ResearchPic2 from '../photos/core-mystery.png';
import ResearchPic3 from '../photos/dynamo-mystery-2.png'
import ResearchPic4 from '../photos/volcanism.png';
import ResearchPic5 from '../photos/ocean-evolution.png';
import './ResearchPage.css';

function ResearchPage() {

    const isWideScreen = useMediaQuery({query: '(min-width: 801px)'});
    const isNarrowScreen = useMediaQuery({query: '(max-width: 800px)'});

    return(
        <div className="research-page">
            <div className="vertical-flex">
                <div id="research-summary-container">
                    <p className="research-text"><strong>I study the formation, evolution, and potential habitability
                    of icy moons.</strong> Conveniently, the processes I model apply to other rocky bodies as well. 
                    Currently, I write code to simulate the structural, thermal, and magnetic history of Jupiter’s moon, Europa, while exploring the geochemical 
                    consequences of my models. Later, I will expand my research scope to other moons in the outer solar system.
                    <br/><br/>
                    Below are some questions that I’m investigating for my primary PhD research, funded by
                    <strong> NASA FINESST</strong>.
                    </p>
                </div>

                <div className={isWideScreen ? "horizontal-flex research-container" : "vertical-flex research-container"}>
                    <img className="research-pic" src={ResearchPic1}/>
                    <p className="research-text"><strong>Origin of ocean-ice shells</strong><br/>
                    Icy moons are arguably the best place to search for extant alien life in our solar 
                    system. Crucially, the composition and habitability of icy moon oceans depend on the 
                    origin of ocean-ice shells. Large icy moons (e.g. Ganymede and Callisto) require 
                    accreted ice to explain most or all of their water budget. However, (rocky) icy 
                    moons like Europa could potentially form their ocean-ice shells by devolatizing 
                    hydrated minerals. The latter case implies high temperature and pressure 
                    rock-water geochemistry as a driver of ocean composition. Currently, I'm 
                    investigating the origin of Europa's hydrocryosphere using geophysical and 
                    geochemical models.
                    </p>
                </div>

                <div className={isWideScreen ? "horizontal-flex research-container" : "vertical-flex research-container"}>
                    <img className="research-pic" src={ResearchPic2}/>
                    <p className="research-text"><strong>Metallic core formation at Europa</strong><br/>
                    For over 20 years, many scientists assume that Europa formed a metallic core during or shortly 
                    after accretion. However, my work (Trinh et al., 2023) shows that rock-metal differentiation may begin 
                    billions of years after accretion, opening up the exciting possibility that Europa's 
                    metallic core formation may still be ongoing (if it happened at all). Metallic core formation 
                    is important because this process extracts redox-sensitive species from the rocky mantle, releases 
                    a heat pulse, and establishes lower bounds on peak internal temperature in Europa's history. 
                    </p>
                </div>

                <div className={isWideScreen ? "horizontal-flex research-container" : "vertical-flex research-container"}>
                    <img className="research-pic" src={ResearchPic3}/>
                    <p className="research-text"><strong>Prospect of an ancient Europan dynamo</strong><br/>
                    The NASA Galileo spacecraft did not detect a core-hosted magnetic field at Europa, 
                    though this does not preclude the existence of a Europan dynamo in the past. 
                    Geodynamos are generated by vigorous convection of conductive material such as 
                    liquid metal in the core (e.g. Earth) or metallic hydrogen (e.g. Jupiter). I will 
                    investigate the magnetic history of Europa following estimates of metallic core age 
                    using thermal evolution models.
                    </p>
                </div>

                <div className={isWideScreen ? "horizontal-flex research-container" : "vertical-flex research-container"}>
                    <img className="research-pic" src={ResearchPic4}/>
                    <p className="research-text"><strong>Prospect of seafloor volcanism at Europa</strong><br/>
                    Silicate volcanism, if it exists, can intensify the heat and chemical energy flux into
                    Europa's ocean. In other words, seafloor volcanism may boost Europa's habitable potential.
                    However, seafloor volcanism requires both silicate melt and transport to the ocean, which
                    is far from assured. My thermal models address when and where silicates melt in
                    Europa's rocky mantle, which directly concerns volcanic potential.
                    </p>
                </div>

                <div className={isWideScreen ? "horizontal-flex research-container" : "vertical-flex research-container"}>
                    <img className="research-pic" src={ResearchPic5}/>
                    <p className="research-text"><strong>Ocean composition and chemistry</strong><br/>
                    Life as we know it requires three things: water (biological solvent), nutrients (e.g., CHNOPS elements),
                    and energy (i.e., disequilibria). There is strong evidence for the former, but it is unclear whether 
                    the remaining two conditions are met. Rock-water reactions and delivery of oxidants across the ice shell may 
                    help sustain chemical disequilibria in Europa's ocean. In addition to thermal modeling, I use
                    computational geochemical software (EQ3/6 and CHNOSZ) to model how Europa's ocean composition could
                    change over time.
                    </p>
                </div>
            </div>
        </div>
    )
}

export default ResearchPage;